source/Conference/Conference.Web/Controllers/ConferenceController.cs
// ==============================================================================================================
// Microsoft patterns & practices
// CQRS Journey project
// ==============================================================================================================
// ©2012 Microsoft. All rights reserved. Certain content used with permission from contributors
// http://go.microsoft.com/fwlink/p/?LinkID=258575
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance 
// with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software distributed under the License is 
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and limitations under the License.
// ==============================================================================================================

namespace Conference.Web.Admin.Controllers
{
    using System;
    using System.Data;
    using System.Web.Mvc;
    using AutoMapper;
    using Infrastructure.Utils;

    public class ConferenceController : Controller
    {
        static ConferenceController()
        {
            Mapper.CreateMap<EditableConferenceInfo, ConferenceInfo>();
        }

        private ConferenceService service;

        private ConferenceService Service
        {
            get { return service ?? (service = new ConferenceService(MvcApplication.EventBus)); }
        }

        public ConferenceInfo Conference { get; private set; }

        // TODO: Locate and Create are the ONLY methods that don't require authentication/location info.

        /// <summary>
        /// We receive the slug value as a kind of cross-cutting value that 
        /// all methods need and use, so we catch and load the conference here, 
        /// so it's available for all. Each method doesn't need the slug parameter.
        /// </summary>
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            var slug = (string)this.ControllerContext.RequestContext.RouteData.Values["slug"];
            if (!string.IsNullOrEmpty(slug))
            {
                this.ViewBag.Slug = slug;
                this.Conference = this.Service.FindConference(slug);

                if (this.Conference != null)
                {
                    // check access
                    var accessCode = (string)this.ControllerContext.RequestContext.RouteData.Values["accessCode"];

                    if (accessCode == null || !string.Equals(accessCode, this.Conference.AccessCode, StringComparison.Ordinal))
                    {
                        filterContext.Result = new HttpUnauthorizedResult("Invalid access code.");
                    }
                    else
                    {
                        this.ViewBag.OwnerName = this.Conference.OwnerName;
                        this.ViewBag.WasEverPublished = this.Conference.WasEverPublished;
                    }
                }
            }

            base.OnActionExecuting(filterContext);
        }

        #region Conference Details

        public ActionResult Locate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Locate(string email, string accessCode)
        {
            var conference = this.Service.FindConference(email, accessCode);
            if (conference == null)
            {
                ModelState.AddModelError(string.Empty, "Could not locate a conference with the provided email and access code.");
                // Preserve input so the user doesn't have to type email again.
                ViewBag.Email = email;

                return View();
            }

            // TODO: This is not very secure. Should use a better authorization infrastructure in a real production system.
            return RedirectToAction("Index", new { slug = conference.Slug, accessCode });
        }

        public ActionResult Index()
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }
            return View(this.Conference);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id,AccessCode,Seats,WasEverPublished")] ConferenceInfo conference)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    conference.Id = GuidUtil.NewSequentialId();
                    this.Service.CreateConference(conference);
                }
                catch (DuplicateNameException e)
                {
                    ModelState.AddModelError("Slug", e.Message);
                    return View(conference);
                }

                return RedirectToAction("Index", new { slug = conference.Slug, accessCode = conference.AccessCode });
            }

            return View(conference);
        }

        public ActionResult Edit()
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }
            return View(this.Conference);
        }

        [HttpPost]
        public ActionResult Edit(EditableConferenceInfo conference)
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                var edited = Mapper.Map(conference, this.Conference);
                this.Service.UpdateConference(edited);
                return RedirectToAction("Index", new { slug = edited.Slug, accessCode = edited.AccessCode });
            }

            return View(this.Conference);
        }

        [HttpPost]
        public ActionResult Publish()
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }

            this.Service.Publish(this.Conference.Id);

            return RedirectToAction("Index", new { slug = this.Conference.Slug, accessCode = this.Conference.AccessCode });
        }

        [HttpPost]
        public ActionResult Unpublish()
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }

            this.Service.Unpublish(this.Conference.Id);

            return RedirectToAction("Index", new { slug = this.Conference.Slug, accessCode = this.Conference.AccessCode });
        }

        #endregion

        #region Seat Types

        public ViewResult Seats()
        {
            return View();
        }

        public ActionResult SeatGrid()
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }

            return PartialView(this.Service.FindSeatTypes(this.Conference.Id));
        }

        public ActionResult SeatRow(Guid id)
        {
            return PartialView("SeatGrid", new SeatType[] { this.Service.FindSeatType(id) });
        }

        public ActionResult CreateSeat()
        {
            return PartialView("EditSeat");
        }

        [HttpPost]
        public ActionResult CreateSeat(SeatType seat)
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                seat.Id = GuidUtil.NewSequentialId();
                this.Service.CreateSeat(this.Conference.Id, seat);

                return PartialView("SeatGrid", new SeatType[] { seat });
            }

            return PartialView("EditSeat", seat);
        }

        public ActionResult EditSeat(Guid id)
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }

            return PartialView(this.Service.FindSeatType(id));
        }

        [HttpPost]
        public ActionResult EditSeat(SeatType seat)
        {
            if (this.Conference == null)
            {
                return HttpNotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    this.Service.UpdateSeat(this.Conference.Id, seat);
                }
                catch (ObjectNotFoundException)
                {
                    return HttpNotFound();
                }

                return PartialView("SeatGrid", new SeatType[] { seat });
            }

            return PartialView(seat);
        }

        [HttpPost]
        public void DeleteSeat(Guid id)
        {
            this.Service.DeleteSeat(id);
        }

        #endregion

        #region Orders

        public ViewResult Orders()
        {
            var orders = this.Service.FindOrders(this.Conference.Id);

            return View(orders);
        }

        #endregion
    }
}

source/Conference/Conference.Web/Views/Conference/Create.cshtml
@model Conference.ConferenceInfo

@{
    ViewBag.Title = "Create Conference";
    ViewBag.PageType = "page_create-conf";
}

<h1 class="page__head page__wrapper">
    Create conference
</h1>
<div class="page__content">
    <div class="page__wrapper content-main_create-conf">
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(false)
            <div class="content-main__wrapper">
                <div class="content-main__main">
                    <div class="content-main__header">Owner information</div>
                    <fieldset class="content">
                        <div class="form__fieldset">
                            @Html.LabelFor(model => model.OwnerName, "Name:*")
                            <div class="form__field">
                                @Html.TextBoxFor(model => model.OwnerName)
                            </div>
                        </div>    
                        <div class="form__fieldset">
                            @Html.LabelFor(model => model.OwnerEmail, "Email address:*")
                            <div class="form__field">
                                @Html.TextBoxFor(model => model.OwnerEmail)
                            </div>
                        </div>   
                        <div class="g-clear"></div>
                    </fieldset>
                    
                    <div class="content-main__header">Conference information</div>
                    <fieldset class="content">
                        <div class="form">
                            <div class="form__fieldset">
                                @Html.LabelFor(model => model.Name, "Title:*")
                                <div class="form__field">
                                    @Html.TextBoxFor(model => model.Name)
                                </div>
                            </div>
                            <div class="form__fieldset">
                                @Html.LabelFor(model => model.Tagline, "Tagline:")
                                <div class="form__field">
                                    @Html.TextBoxFor(model => model.Tagline)
                                </div>
                            </div>
                            @*<div class="form__fieldset">
                                <label class="form__label">Event logo:</label>
                                <div class="form__but-box form__but-box_file">
                                    <button class="form__but">Upload</button>
                                </div>
                                <div class="form__field form__field_file">
                                    <div class="form__field_file-input">
                                        <input type="file" size="28" class="inputFile" onchange='document.getElementById("fileName").value=this.value' />
                                    </div>
                                    <input id="fileName" />
                                </div>
                                <div class="form__file-logo">
                                    <img src="tmp/pic_3.jpg" /><span class="form__file-logo__valign"></span>
                                    <span class="form__file-logo__txt">Your logo</span>
                                </div>
                            </div>*@
                            <div class="form__fieldset">
                                @Html.LabelFor(model => model.Slug, "Slug/conference code:*")
                                <div class="form__field">
                                    @Html.TextBoxFor(model => model.Slug)
                                </div>
                            </div>
                            <div class="form__fieldset">
                                @Html.LabelFor(model => model.Location, "Location:*")
                                <div class="form__field">
                                    @Html.TextBoxFor(model => model.Location)
                                </div>
                            </div>
                            <div class="form__fieldset">
                                @Html.LabelFor(model => model.TwitterSearch, "Twitter search:")
                                <div class="form__field">
                                    @Html.TextBoxFor(model => model.TwitterSearch)
                                </div>
                            </div>
                            <div class="form__fieldset form__fieldset_textarea">
                                @Html.LabelFor(model => model.Description, "Description:*")
                                <div class="form__field">
                                    @Html.TextAreaFor(model => model.Description)
                                </div>
                            </div>
                            <div class="g-clear"></div>
                        </div>
                        @*<div class="form form__col3">
                            <div class="form__fieldset">
                                <label class="form__label">Front-page date format:</label>
                                <select>
                                    <option>Apr 20, 15:00</option>
                                    <option>Apr 20, 2012</option>
                                    <option>Apr 20-23, 2012</option>
                                    <option>Apr 20, 3:00 PM</option>
                                </select>
                            </div>
                            <div class="form__fieldset">
                                <label class="form__label">Start date-time:</label>
                                <select>
                                    <option>9:00 AM</option>
                                    <option>10:00 AM</option>
                                    <option>11:00 AM</option>
                                </select>
                            </div>
                            <div class="form__fieldset">
                                <label class="form__label">End date-time:</label>
                                <select>
                                    <option>10:00 AM</option>
                                    <option>11:00 AM</option>
                                    <option>12:00 AM</option>
                                </select>
                            </div>
                            <div class="g-clear"></div>
                        </div>*@
                        <div class="form">
@*                        <div class="form form__col3">
                            <div class="form__fieldset">
                                <label class="form__label">Time zone:</label>
                                <select>
                                    <option>UTC-8</option>
                                    <option>UTC-9</option>
                                    <option>UTC-7</option>
                                </select>
                            </div>*@
                            <div class="form__fieldset">
                                @Html.LabelFor(model => model.StartDate, "Start date:*")
                                @Html.Hidden("StartDate", Model != null ? Model.StartDate.ToString("yyyy/MM/dd") : null, new { @class="inline-datepicker" })
                            </div>
                            <div class="form__fieldset">
                                @Html.LabelFor(model => model.EndDate, "End date:*")
                                @Html.Hidden("EndDate",  Model != null ? Model.EndDate.ToString("yyyy/MM/dd") : null, new { @class="inline-datepicker" })
                            </div>
                            <div class="g-clear"></div>
                        </div>
                    </fieldset>
                    <div class="nav content-main__nav">
                        <button class="nav__right">
                            Save conference
                        </button>
                    </div>
                </div>
            </div>@*
            <div class="content-main__aside">
                <div class="content-main__header"></div>
                
            </div>
            *@<div class="g-clear"></div>
        }
    </div>
</div>

source/Conference/Conference.Web/Views/Conference/CreateDiscount.cshtml
@model Conference.Web.Admin.Models.DiscountInfo

@{
    ViewBag.Title = "Discount";
}

<h2>Discount</h2>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(model => model.Code)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Code)
            @Html.ValidationMessageFor(model => model.Code)
        </div>        
        <div class="editor-label">
            @Html.LabelFor(model => model.Percentage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Percentage)
            @Html.ValidationMessageFor(model => model.Percentage)
        </div>        
    </fieldset>
        <p>
            <input type="submit" value="Create" />
        </p>
		}

source/Conference/Conference.Web/Views/Conference/Details.cshtml
@model Conference.ConferenceInfo

@{
    ViewBag.Title = "Details";
}

<p style="text-align: right">
    @Html.DisplayFor(model => model.OwnerName)
</p>

@{ Html.RenderPartial("Navigation"); }

<h2>Details</h2>

<fieldset>
    <legend>Owner Information</legend>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.OwnerName)
    </div>
    <div class="display-label">
        @Html.DisplayFor(model => model.OwnerName)
    </div>        

    <div class="display-label">
        @Html.DisplayNameFor(model => model.OwnerEmail)
    </div>
    <div class="display-label">
        @Html.DisplayFor(model => model.OwnerEmail)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.AccessCode)
    </div>
    <div class="display-label">
        @Html.DisplayFor(model => model.AccessCode)
    </div>
</fieldset>

<fieldset>
    <legend>Conference Information</legend>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Slug)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Slug)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StartDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.EndDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndDate)
    </div>

@{ var action = Model.IsPublished ? "Unpublish" : "Publish"; }
@using (Html.BeginForm(action, "Conference")) {
    <div>
        @Html.HiddenFor(model => model.Id)
        @Html.DisplayNameFor(model => model.IsPublished) @Html.DisplayFor(model => model.IsPublished)
        <a href="javascript:$('form').submit();">@action</a>
    </div>
}
    <div class="display-label">
    </div>
</fieldset>

<div>
        @Html.ActionLink("Edit", "Edit", new { id = @Model.Id }, null)
</div>

source/Conference/Conference.Web/Views/Conference/EditSeat.cshtml
@model Conference.SeatType

<tr @if (Model != null) {
    @:data-pkey="@Model.Id"
}>
    <td>
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
    </td>
    <td>
        @Html.EditorFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)
    </td>
    <td>
        @Html.EditorFor(model => model.Quantity)
        @Html.ValidationMessageFor(model => model.Quantity)
    </td>
    <td>
        @Html.EditorFor(model => model.Price)
        @Html.ValidationMessageFor(model => model.Price)
    </td>
    <td>
@if (ViewContext.RouteData.Values["Action"].ToString() == "EditSeat") {
        <button class="form__but editRow">Save</button><button class="form__but cancelEditRow">Cancel</button>
} else {
        <button class="form__but createRow">Create</button><button class="form__but cancelCreateRow">Cancel</button>
}
    </td>
</tr>

source/Conference/Conference.Web/Views/Conference/Index.cshtml
@model Conference.ConferenceInfo

@{
    ViewBag.Title = "My Conference";
    ViewBag.PageType = "page_create-conf";
}

@section Navigation
{
    <div class="quick__login">@Model.OwnerName</div>
}

@section PageNavigation {
    @Html.Partial("Navigation")
}

<h1 class="page__head page__wrapper page_create-conf">
    Conference details
</h1>
<div class="page__content">
    <div class="page__wrapper content-main_create-conf">
            <div class="content-main__wrapper">
                <div class="content-main__main">
                    <div class="content-main__header">Owner information</div>
                    <fieldset class="content">
                        <div class="form__fieldset">
                            <label>Name:</label>
                            <div class="form__field">
                                <pre>@Model.OwnerName</pre>
                            </div>
                        </div>    
                        <div class="form__fieldset">
                            <label>Email address:</label>
                            <div class="form__field">
                                <pre>@Model.OwnerEmail</pre>
                            </div>
                        </div>
                        <div class="form__fieldset">
                            <label>Access Code:</label>
                            <div class="form__field">
                                <pre>@Model.AccessCode</pre>
                            </div>
                        </div>   
                        <div class="g-clear"></div>
                    </fieldset>
                    
                    <div class="content-main__header">Conference information</div>
                    <fieldset class="content">
                        <div class="form">
                            <div class="form__fieldset">
                                <label>Title:</label>
                                <div class="form__field">
                                    <pre>@Model.Name</pre>
                                </div>
                            </div>
                            <div class="form__fieldset">
                                <label>Tagline:</label>
                                <div class="form__field">
                                    <pre>@Model.Tagline</pre>
                                </div>
                            </div>
                            <div class="form__fieldset">
                                <label>Slug/conference code:</label>
                                <div class="form__field">
                                    <pre>@Model.Slug</pre>
                                </div>
                            </div>  
                            <div class="form__fieldset">
                                <label>Location:</label>
                                <div class="form__field">
                                    <pre>@Model.Location</pre>
                                </div>
                            </div>
                            <div class="form__fieldset">
                                <label>Twitter search:</label>
                                <div class="form__field">
                                    <pre>@Model.TwitterSearch</pre>
                                </div>
                            </div>
                            <div class="form__fieldset form__fieldset_textarea">
                                <label>Description:</label>
                                <div class="form__field">
                                    <pre style="height: auto">@Model.Description</pre>
                                </div>
                            </div>
                            <div class="form__fieldset">
                                <label>Start date:</label>
                                <div class="form__field">
                                    <pre>@Model.StartDate.ToString("yyyy/MM/dd")</pre>
                                </div>
                            </div>
                            <div class="form__fieldset">
                                <label>End date:</label>
                                <div class="form__field">
                                    <pre>@Model.EndDate.ToString("yyyy/MM/dd")</pre>
                                </div>
                            </div>
                            <div class="g-clear"></div>
                        </div>
                    </fieldset>
                    <div class="nav content-main__nav">
                        <a class="nav__left" href="@Url.Action("Edit", new { slug = @Model.Slug })">Edit</a>
                        @{ var action = Model.IsPublished ? "Unpublish" : "Publish"; }
                        @using (Html.BeginForm(action, "Conference", new { Model.Id })) {
                            <button type="submit" class="nav__right">@action</button>
                        }
                        <a class="nav__right" style="margin-right: 40px;" href="@Url.Action("Seats", new { slug = ViewBag.Slug })">Configure seats</a>
                    </div>
                </div>
            </div><div class="g-clear"></div>
    </div>
</div>

source/Conference/Conference.Web/Views/Conference/Locate.cshtml
@{
    ViewBag.Title = "Access Conference";
}

<div class="page__content">
    <div class="page__wrapper">
    @using (Html.BeginForm())
    {
        <div class="content-main__header">Login</div>
        @Html.ValidationSummary(false)
        <fieldset class="content content_login">

            <p>Please enter your email and conference access code to manage your conference:</p>
            <div class="form">
                <div class="form__fieldset">
                    <label class="form__label">Login (E-mail):<span>*</span></label>
                    <div class="form__field">
                        <input type="text" name="email" value="@ViewBag.Email" data-val="true" data-val-required="e-mail field is required."  />
                    </div>
                </div>
                <div class="form__fieldset">
                    <label class="form__label">Access code:<span>*</span></label>
                    <div class="form__field">
                        <input type="password" name="accessCode" data-val="true" data-val-required="Access code is required."  />
                    </div>
                </div>
                <div class="form__but-box">
                    <button class="form__but">Login</button>
                </div>
                <div class="g-clear"></div>
            </div>
        </fieldset>
        <div class="g-clear"></div>
    }
    </div>
</div>

source/Conference/Conference.Web/Views/Conference/Navigation.cshtml
<div class="page__menu menu">
    <ul class="menu__list">
        <li class="menu__item"><a class="menu__back" href="@Url.Action("Index", "Home")"></a></li>
        <li class="menu__item @this.RenderIfActive("Index")"><a href="@Url.Action("Index", new { slug = ViewBag.Slug })">Conference details</a></li>
        <li class="menu__item @this.RenderIfActive("Seats")"><a href="@Url.Action("Seats", new { slug = ViewBag.Slug })">Seat types</a></li>
        <li class="menu__item @this.RenderIfActive("Discount")><a href="@Url.Action("Discount", new { slug = ViewBag.Slug })">Discounts</a></li>
        @*<li class="menu__item"><a href="#">Venue Details</a></li>*@
        <li class="menu__item @this.RenderIfActive("Orders")"><a href="@Url.Action("Orders", new { slug = ViewBag.Slug })">Registrations</a></li>
        @*<li class="menu__item"><a href="#">Sessions</a></li>*@
    </ul>
</div>

@helper RenderIfActive(string actionName)
{
    if (string.Equals(Url.RequestContext.RouteData.Values["action"], actionName))
    {<text>menu__item_active</text>}
}

source/Conference/Conference.Web/Views/Conference/SeatGrid.cshtml
@model IEnumerable<Conference.SeatType>

@foreach (var item in Model) {
    <tr data-pkey="@item.Id">
        <td>
            <a href="#makeRowEditable" class="makeRowEditable">@item.Name</a> 
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            $@Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @if (ViewBag.WasEverPublished) {
                <span title="The conference has been published at least once before. Cannot delete seat types.">Delete</span>
            } else {
                <a href="#deleteRow" class="deleteRow">Delete</a>
            }
        </td>
    </tr>
}